USE master;
DROP DATABASE db_3a9780a8d440;
--DROP DATABASE system_master;
--DROP DATABASE management_db;
--USE system_master;
--USE management_db;
--USE client_master;
--SELECT *
--FROM organization_structures;
--SELECT *
--FROM users;
--SELECT *
--FROM user_types;
--SELECT *
--FROM user_role -- GO
--SELECT *
--FROM user_relation -- GO
--SELECT *
--FROM clients;
--SELECT *
--FROM business;
--SELECT *
--FROM user_has_clients;
--DROP DATABASE d52ce619a8ec_db;
--SELECT *
--FROM sys.databases
--WHERE name <> '';
--USE db_0528594fe389;
--SELECT *
--FROM sys.tables
--WHERE name <> '';
GO